({
  katexConfig: {
  "macros": {}
},
  
  mathjaxConfig: {
  "tex": {
    "macros": {
      "R": "\\mathbb{R}",
      "C": "\\mathbb{C}",
      "Z": "\\mathbb{Z}",
      "N": "\\mathbb{N}",
      "Q": "\\mathbb{Q}",

      "pd": ["\\frac{\\partial #1}{\\partial #2}", 2],
      "dd": ["\\frac{d\\, #1}{d\\, #2}", 2],

      "inner": ["\\langle #1,\\, #2 \\rangle", 2],
      "norm": ["\\left\\| #1 \\right\\|", 1],
      "abs": ["\\left| #1 \\right|", 1],

      "valence": ["\\left\\{\\begin{smallmatrix} #1 \\\\ #2 \\end{smallmatrix}\\right\\}", 2],

      "wedge": "\\wedge",
      "ext": "\\mathbf{d}",
      "hodge": "\\star",

      "del": "\\nabla",
      "lap": "\\nabla^2",
      "grad": "\\nabla",
      "divg": "\\nabla \\cdot",
      "curl": "\\nabla \\times",

      "affconn": ["\\Gamma^{#1}_{#2 #3}", 3],
      "affconns": ["\\Gamma^{#1}_{\\;\\; #2 #3}", 3],
      "chris": ["\\Gamma^{#1}_{#2 #3}", 3],

      "lie": ["\\mathcal{L}_{#1}", 1],
      "commut": ["\\left[ #1,\\, #2 \\right]", 2],
      "pois": ["\\left\\{ #1,\\, #2 \\right\\}", 2],

      "tr": "\\operatorname{tr}",
      "det": "\\det",
      "diag": "\\operatorname{diag}",
      "rank": "\\operatorname{rank}",
      "dim": "\\dim",
      "ker": "\\ker",
      "im": "\\operatorname{im}",
      "span": "\\operatorname{span}",

      "half": "\\tfrac{1}{2}",
      "affrac": ["\\frac{#1}{#2}", 2],
      "eval": ["\\left. #1 \\right|_{#2}", 2],
      "conj": ["\\overline{#1}", 1],
      "dual": ["#1^{*}", 1],
      "tens": "\\otimes",
      "dsum": "\\oplus",
      "iso": "\\cong",
      "hom": "\\operatorname{Hom}",

      "mat": ["\\begin{pmatrix} #1 \\end{pmatrix}", 1],
      "bmat": ["\\begin{bmatrix} #1 \\end{bmatrix}", 1],
      "vmat": ["\\begin{vmatrix} #1 \\end{vmatrix}", 1],
      "cmat": ["\\left\\{\\begin{matrix} #1 \\end{matrix}\\right\\}", 1],
      "smat": ["\\left(\\begin{smallmatrix} #1 \\end{smallmatrix}\\right)", 1],
      "augmat": ["\\left[\\begin{array}{#1} #2 \\end{array}\\right]", 2],
      "col": ["\\begin{pmatrix} #1 \\end{pmatrix}", 1],
      "row": ["\\begin{pmatrix} #1 \\end{pmatrix}", 1],
      "imat": ["\\mathbf{I}_{#1}", 1],
      "zmat": ["\\mathbf{0}_{#1}", 1],
      "tp": "^{\\mathsf{T}}",
      "inv": "^{-1}",
      "herm": "^{\\dagger}",

      "cases": ["\\begin{cases} #1 \\end{cases}", 1],

      "bvec": ["\\mathbf{#1}", 1],
      "uvec": ["\\hat{\\mathbf{#1}}", 1],
      "dvec": ["\\dot{\\vec{#1}}", 1],
      "ddvec": ["\\ddot{\\vec{#1}}", 1],
      "metric": ["g_{#1 #2}", 2],
      "invmetric": ["g^{#1 #2}", 2],
      "covd": ["\\nabla_{#1}", 1],
      "ulteq": "\\asymp",

      "ket": ["\\left| #1 \\right\\rangle", 1],
      "bra": ["\\left\\langle #1 \\right|", 1],
      "braket": ["\\left\\langle #1 \\middle| #2 \\right\\rangle", 2],
      "ketbra": ["\\left| #1 \\right\\rangle\\!\\left\\langle #2 \\right|", 2],
      "mel": ["\\left\\langle #1 \\middle| #2 \\middle| #3 \\right\\rangle", 3],
      "expval": ["\\left\\langle #1 \\right\\rangle", 1],
      "comm": ["\\left[ #1,\\, #2 \\right]", 2],
      "acomm": ["\\left\\{ #1,\\, #2 \\right\\}", 2],
      "dag": "\\dagger",
      "hc": "\\text{h.c.}",
      "cc": "\\text{c.c.}",
      "op": ["\\hat{#1}", 1],
      "opad": ["\\hat{#1}^\\dagger", 1],
      "hilb": ["\\mathcal{#1}", 1],
      "ident": "\\mathbb{1}",
      "paulix": "\\sigma_x",
      "pauliy": "\\sigma_y",
      "pauliz": "\\sigma_z",
      "pauli": ["\\sigma_{#1}", 1],
      "spinup": "\\left| \\!\\uparrow \\right\\rangle",
      "spindn": "\\left| \\!\\downarrow \\right\\rangle",

      "slashed": ["\\not{\\! #1}", 1],
      "Lag": "\\mathcal{L}",
      "Ham": "\\mathcal{H}",
      "action": "\\mathcal{S}",
      "pint": "\\int \\!\\mathcal{D}",
      "norder": ["{:\\! #1 \\!:}", 1],
      "torder": ["\\mathcal{T}\\left\\{ #1 \\right\\}", 1],
      "prop": ["\\langle 0 | \\mathcal{T}\\{ #1 \\} | 0 \\rangle", 1],
      "vev": ["\\langle 0 | #1 | 0 \\rangle", 1],
      "dslash": ["\\not{\\!\\partial}", 0],

      "ga": ["\\mathbf{e}_{#1}", 1],
      "gp": "\\wedge",
      "gd": "\\cdot",
      "gin": "\\,\\lrcorner\\,",
      "grev": ["\\widetilde{#1}", 1],
      "ginv": ["#1^{-1}", 1],
      "grade": ["\\langle #1 \\rangle_{#2}", 2],
      "mvec": ["\\mathbf{#1}", 1],
      "rotor": ["\\mathbf{#1}", 1],
      "pseudo": "\\mathbf{I}",
      "gexp": ["e^{#1}", 1],
      "cl": ["\\mathrm{Cl}(#1)", 1],
      "cln": ["\\mathrm{Cl}_{#1,#2}", 2],
      "spin": ["\\mathrm{Spin}(#1)", 1],
      "pin": ["\\mathrm{Pin}(#1)", 1],

      "grp": ["\\mathbf{#1}", 1],
      "SU": ["\\mathrm{SU}(#1)", 1],
      "SO": ["\\mathrm{SO}(#1)", 1],
      "SL": ["\\mathrm{SL}(#1)", 1],
      "GL": ["\\mathrm{GL}(#1)", 1],
      "UU": ["\\mathrm{U}(#1)", 1],
      "OO": ["\\mathrm{O}(#1)", 1],
      "Sp": ["\\mathrm{Sp}(#1)", 1],
      "sualg": ["\\mathfrak{su}(#1)", 1],
      "soalg": ["\\mathfrak{so}(#1)", 1],
      "slalg": ["\\mathfrak{sl}(#1)", 1],
      "glalg": ["\\mathfrak{gl}(#1)", 1],
      "ualg": ["\\mathfrak{u}(#1)", 1],
      "spalg": ["\\mathfrak{sp}(#1)", 1],
      "lalg": ["\\mathfrak{#1}", 1],
      "rep": ["\\mathbf{#1}", 1],
      "irr": "\\operatorname{Irr}",
      "chars": "\\operatorname{char}",
      "aut": "\\operatorname{Aut}",
      "inn": "\\operatorname{Inn}",
      "out": "\\operatorname{Out}",
      "orb": ["\\operatorname{Orb}(#1)", 1],
      "stab": ["\\operatorname{Stab}(#1)", 1],
      "nsg": "\\trianglelefteq",
      "sdp": "\\rtimes",
      "gact": "\\curvearrowright",
      "conj_class": ["\\operatorname{Cl}(#1)", 1],
      "cent": ["Z(#1)", 1],
      "nmlz": ["N(#1)", 1],
      "idx": ["[#1 : #2]", 2],

      "cat": ["\\mathsf{#1}", 1],
      "Set": "\\mathsf{Set}",
      "Grp": "\\mathsf{Grp}",
      "Ab": "\\mathsf{Ab}",
      "Top": "\\mathsf{Top}",
      "Vect": "\\mathsf{Vect}",
      "Ring": "\\mathsf{Ring}",
      "Mod": "\\mathsf{Mod}",
      "Fun": ["\\operatorname{Fun}(#1, #2)", 2],
      "Ob": "\\operatorname{Ob}",
      "Mor": "\\operatorname{Mor}",
      "End": "\\operatorname{End}",
      "Aut": "\\operatorname{Aut}",
      "Id": "\\operatorname{Id}",
      "colim": "\\operatorname{colim}",
      "lim": "\\varprojlim",
      "colimit": "\\varinjlim",
      "natiso": "\\cong",
      "natto": "\\Rightarrow",
      "adj": "\\dashv",
      "yon": "\\mathsf{y}",
      "opcat": ["#1^{\\mathrm{op}}", 1],

      "sup": "\\operatorname{sup}",
      "inf": "\\operatorname{inf}",
      "limsup": "\\limsup",
      "liminf": "\\liminf",
      "eps": "\\varepsilon",
      "dl": "\\delta",
      "seq": ["\\left\\{ #1 \\right\\}_{#2}", 2],
      "subseq": ["\\left\\{ #1 \\right\\}_{#2}", 2],
      "conv": "\\to",
      "nbd": ["N_{#1}(#2)", 2],

      "emf": "\\mathcal{E}",
      "epsn": "\\varepsilon_0",
      "mun": "\\mu_0",
      "rhoq": "\\rho",
      "Jcur": "\\mathbf{J}",
      "Efield": "\\mathbf{E}",
      "Bfield": "\\mathbf{B}",
      "Afield": "\\mathbf{A}",
      "Vpot": "\\Phi",
      "maxw": ["\\partial_{#1}", 1],
      "dAl": "\\Box",
      "fmn": ["F_{#1 #2}", 2],
      "fmnu": ["F^{#1 #2}", 2],

      "Lagr": ["L(#1, \\dot{#1}, t)", 1],
      "genp": ["p_{#1}", 1],
      "genq": ["q_{#1}", 1],
      "fdv": ["\\frac{\\delta #1}{\\delta #2}", 2],
      "pb": ["\\left\\{ #1,\\, #2 \\right\\}", 2],
      "phsp": "\\Gamma",
      "config": "\\mathcal{Q}",

      "res": ["\\operatorname{Res}_{#1}", 1],
      "oint": "\\oint",
      "Log": "\\operatorname{Log}",
      "Arg": "\\operatorname{Arg}",
      "Re": "\\operatorname{Re}",
      "Im": "\\operatorname{Im}",
      "cder": ["f'(#1)", 1],
      "holo": "\\text{holomorphic}",
      "mero": "\\text{meromorphic}",
      "wind": ["\\operatorname{Ind}_{#1}(#2)", 2],

      "graph": ["G = (#1, #2)", 2],
      "vtx": "V",
      "edg": "E",
      "gadj": "\\sim",
      "deg": ["\\deg(#1)", 1],
      "diam": "\\operatorname{diam}",
      "chrom": "\\chi",
      "chromp": ["P(#1, k)", 1],
      "indep": "\\alpha",
      "cliq": "\\omega",
      "comp": ["\\overline{#1}", 1],
      "kn": ["K_{#1}", 1],
      "kmn": ["K_{#1,#2}", 2],
      "cn": ["C_{#1}", 1],
      "pn": ["P_{#1}", 1],

      "qbit": ["\\left| #1 \\right\\rangle", 1],
      "qzero": "\\left| 0 \\right\\rangle",
      "qone": "\\left| 1 \\right\\rangle",
      "qplus": "\\frac{1}{\\sqrt{2}}(\\left|0\\right\\rangle + \\left|1\\right\\rangle)",
      "qminus": "\\frac{1}{\\sqrt{2}}(\\left|0\\right\\rangle - \\left|1\\right\\rangle)",
      "CNOT": "\\operatorname{CNOT}",
      "Had": "\\mathbf{H}",
      "Xgate": "\\mathbf{X}",
      "Ygate": "\\mathbf{Y}",
      "Zgate": "\\mathbf{Z}",
      "Tgate": "\\mathbf{T}",
      "Sgate": "\\mathbf{S}",
      "cgate": ["C\\text{-}#1", 1],
      "densm": "\\rho",
      "ptrace": ["\\operatorname{Tr}_{#1}", 1],
      "fid": ["F(#1, #2)", 2],

      "coker": "\\operatorname{coker}",
      "exact": ["0 \\to #1 \\to #2 \\to #3 \\to 0", 3],
      "ses": ["0 \\to #1 \\to #2 \\to #3 \\to 0", 3],
      "quotient": ["#1/#2", 2],
      "embed": "\\hookrightarrow",
      "surj": "\\twoheadrightarrow",
      "pullback": ["#1^{*}", 1],
      "pushfwd": ["#1_{*}", 1],

      "v": ["\\vec{#1}", 1]
    }
  },
  "options": {},
  "loader": {}
},
  
  mermaidConfig: {
  "startOnLoad": false
},
})